
  services:
    app:

      image: ${IMAGE:-ksanthoshkumar25/java-cicd-demo:latest}

      container_name: java-cicd-demo

      ports:
        - "8080:8080"

      restart: unless-stopped

      healthcheck:
        test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
        interval: 30s
        timeout: 3s
        retries: 3

